name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      if: (github.ref == 'refs/heads/master' || github.event_name == 'push') && github.repository == 'dat-adi/novel-crawlers'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag datadi/novel-crawlers

    - name: Publish Docker Image
      if: (github.ref == 'refs/heads/master' || github.event_name == 'push') && github.repository == 'dat-adi/novel-crawlers'
      run: docker push datadi/novel-crawlers
